from dataclasses import dataclass

@dataclass
class ModellingDataContract:
    """ Holds details for defining modelling terms in a single place.
    """
    
    ID_COL = "match_ID"
    RESPONSE_SCORES = "scores"
    RESPONSE_CONCEDES = "concedes"
           
    # Scores
    feature_list_scores = [
        'type_Kick',
        'type_Handball',
        'type_Carry',
        'type_Uncontested Mark',
        'type_Contested Mark',
        'type_Loose Ball Get',
        'type_Hard Ball Get',
        'type_Spoil',
        'type_Gather',
        'type_Free For',
        'type_Knock On',
        'type_Shot',
        'type_Tackle',
        'type_Error',
        'outcome_effective',
        'outcome_ineffective',
        'outcome_clanger',
        'type_Kick_outcome_effective',
        'type_Kick_outcome_ineffective',
        'type_Kick_outcome_clanger',
        'type_Handball_outcome_effective',
        'type_Handball_outcome_ineffective',
        'type_Handball_outcome_clanger',
        'type_Carry_outcome_effective',
        'type_Carry_outcome_ineffective',
        'type_Carry_outcome_clanger',
        'type_Uncontested Mark_outcome_effective',
        'type_Uncontested Mark_outcome_ineffective',
        'type_Uncontested Mark_outcome_clanger',
        'type_Contested Mark_outcome_effective',
        'type_Contested Mark_outcome_ineffective',
        'type_Contested Mark_outcome_clanger',
        'type_Loose Ball Get_outcome_effective',
        'type_Loose Ball Get_outcome_ineffective',
        'type_Loose Ball Get_outcome_clanger',
        'type_Hard Ball Get_outcome_effective',
        'type_Hard Ball Get_outcome_ineffective',
        'type_Hard Ball Get_outcome_clanger',
        'type_Spoil_outcome_effective',
        'type_Spoil_outcome_ineffective',
        'type_Spoil_outcome_clanger',
        'type_Gather_outcome_effective',
        'type_Gather_outcome_ineffective',
        'type_Gather_outcome_clanger',
        'type_Free For_outcome_effective',
        'type_Free For_outcome_ineffective',
        'type_Free For_outcome_clanger',
        'type_Knock On_outcome_effective',
        'type_Knock On_outcome_ineffective',
        'type_Knock On_outcome_clanger',
        'type_Shot_outcome_effective',
        'type_Shot_outcome_ineffective',
        'type_Shot_outcome_clanger',
        'type_Tackle_outcome_effective',
        'type_Tackle_outcome_ineffective',
        'type_Tackle_outcome_clanger',
        'type_Error_outcome_effective',
        'type_Error_outcome_ineffective',
        'type_Error_outcome_clanger',
        'quarter',
        'quarter_seconds',
        'overall_seconds',
        'start_x',
        'start_y',
        'end_x',
        'end_y',
        'dx',
        'dy',
        'movement',
        'type_Kick.1',
        'type_Handball.1',
        'type_Carry.1',
        'type_Uncontested Mark.1',
        'type_Contested Mark.1',
        'type_Loose Ball Get.1',
        'type_Hard Ball Get.1',
        'type_Spoil.1',
        'type_Gather.1',
        'type_Free For.1',
        'type_Knock On.1',
        'type_Shot.1',
        'type_Tackle.1',
        'type_Error.1',
        'outcome_effective.1',
        'outcome_ineffective.1',
        'outcome_clanger.1',
        'type_Kick_outcome_effective.1',
        'type_Kick_outcome_ineffective.1',
        'type_Kick_outcome_clanger.1',
        'type_Handball_outcome_effective.1',
        'type_Handball_outcome_ineffective.1',
        'type_Handball_outcome_clanger.1',
        'type_Carry_outcome_effective.1',
        'type_Carry_outcome_ineffective.1',
        'type_Carry_outcome_clanger.1',
        'type_Uncontested Mark_outcome_effective.1',
        'type_Uncontested Mark_outcome_ineffective.1',
        'type_Uncontested Mark_outcome_clanger.1',
        'type_Contested Mark_outcome_effective.1',
        'type_Contested Mark_outcome_ineffective.1',
        'type_Contested Mark_outcome_clanger.1',
        'type_Loose Ball Get_outcome_effective.1',
        'type_Loose Ball Get_outcome_ineffective.1',
        'type_Loose Ball Get_outcome_clanger.1',
        'type_Hard Ball Get_outcome_effective.1',
        'type_Hard Ball Get_outcome_ineffective.1',
        'type_Hard Ball Get_outcome_clanger.1',
        'type_Spoil_outcome_effective.1',
        'type_Spoil_outcome_ineffective.1',
        'type_Spoil_outcome_clanger.1',
        'type_Gather_outcome_effective.1',
        'type_Gather_outcome_ineffective.1',
        'type_Gather_outcome_clanger.1',
        'type_Free For_outcome_effective.1',
        'type_Free For_outcome_ineffective.1',
        'type_Free For_outcome_clanger.1',
        'type_Knock On_outcome_effective.1',
        'type_Knock On_outcome_ineffective.1',
        'type_Knock On_outcome_clanger.1',
        'type_Shot_outcome_effective.1',
        'type_Shot_outcome_ineffective.1',
        'type_Shot_outcome_clanger.1',
        'type_Tackle_outcome_effective.1',
        'type_Tackle_outcome_ineffective.1',
        'type_Tackle_outcome_clanger.1',
        'type_Error_outcome_effective.1',
        'type_Error_outcome_ineffective.1',
        'type_Error_outcome_clanger.1',
        'quarter.1',
        'quarter_seconds.1',
        'overall_seconds.1',
        'start_x.1',
        'start_y.1',
        'end_x.1',
        'end_y.1',
        'dx.1',
        'dy.1',
        'movement.1',
        'type_Kick.2',
        'type_Handball.2',
        'type_Carry.2',
        'type_Uncontested Mark.2',
        'type_Contested Mark.2',
        'type_Loose Ball Get.2',
        'type_Hard Ball Get.2',
        'type_Spoil.2',
        'type_Gather.2',
        'type_Free For.2',
        'type_Knock On.2',
        'type_Shot.2',
        'type_Tackle.2',
        'type_Error.2',
        'outcome_effective.2',
        'outcome_ineffective.2',
        'outcome_clanger.2',
        'type_Kick_outcome_effective.2',
        'type_Kick_outcome_ineffective.2',
        'type_Kick_outcome_clanger.2',
        'type_Handball_outcome_effective.2',
        'type_Handball_outcome_ineffective.2',
        'type_Handball_outcome_clanger.2',
        'type_Carry_outcome_effective.2',
        'type_Carry_outcome_ineffective.2',
        'type_Carry_outcome_clanger.2',
        'type_Uncontested Mark_outcome_effective.2',
        'type_Uncontested Mark_outcome_ineffective.2',
        'type_Uncontested Mark_outcome_clanger.2',
        'type_Contested Mark_outcome_effective.2',
        'type_Contested Mark_outcome_ineffective.2',
        'type_Contested Mark_outcome_clanger.2',
        'type_Loose Ball Get_outcome_effective.2',
        'type_Loose Ball Get_outcome_ineffective.2',
        'type_Loose Ball Get_outcome_clanger.2',
        'type_Hard Ball Get_outcome_effective.2',
        'type_Hard Ball Get_outcome_ineffective.2',
        'type_Hard Ball Get_outcome_clanger.2',
        'type_Spoil_outcome_effective.2',
        'type_Spoil_outcome_ineffective.2',
        'type_Spoil_outcome_clanger.2',
        'type_Gather_outcome_effective.2',
        'type_Gather_outcome_ineffective.2',
        'type_Gather_outcome_clanger.2',
        'type_Free For_outcome_effective.2',
        'type_Free For_outcome_ineffective.2',
        'type_Free For_outcome_clanger.2',
        'type_Knock On_outcome_effective.2',
        'type_Knock On_outcome_ineffective.2',
        'type_Knock On_outcome_clanger.2',
        'type_Shot_outcome_effective.2',
        'type_Shot_outcome_ineffective.2',
        'type_Shot_outcome_clanger.2',
        'type_Tackle_outcome_effective.2',
        'type_Tackle_outcome_ineffective.2',
        'type_Tackle_outcome_clanger.2',
        'type_Error_outcome_effective.2',
        'type_Error_outcome_ineffective.2',
        'type_Error_outcome_clanger.2',
        'quarter.2',
        'quarter_seconds.2',
        'overall_seconds.2',
        'start_x.2',
        'start_y.2',
        'end_x.2',
        'end_y.2',
        'dx.2',
        'dy.2',
        'movement.2',
        'team_1',
        'team_2',
        'time_delta1',
        'time_delta2',
        'dx_a01',
        'dy_a01',
        'move_a01',
        'dx_a02',
        'dy_a02',
        'move_a02',
        'goalscore_team',
        'goalscore_opponent',
        'goalscore_diff'
    ]
    monotone_constraints_scores = {}
    
    # Concedes
    feature_list_concedes = []
    monotone_constraints_concedes = {}    